name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-24.04

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install -y \
            openjdk-11-jdk git zip unzip python3-pip \
            libncurses6 libncurses-dev libffi-dev libssl-dev libsqlite3-dev build-essential \
            liblzma-dev libbz2-dev libreadline-dev xz-utils tk-dev \
            libxml2-dev libxmlsec1-dev libjpeg-dev zlib1g-dev \
            autoconf automake libtool pkg-config curl

      - name: Install Android SDK Command line tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          cd $ANDROID_SDK_ROOT/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools.zip
          rm commandlinetools.zip
          mv cmdline-tools latest

      - name: Set PATH env variable
        run: echo "PATH=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin:${ANDROID_SDK_ROOT}/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

      - name: Upgrade pip and install buildozer
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          pip install buildozer

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
