name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'   # Phiên bản Python mới nhất hiện tại

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools git zip unzip openjdk-11-jdk \
            libncurses5 libffi-dev libssl-dev libsqlite3-dev build-essential liblzma-dev \
            libbz2-dev libreadline-dev libsqlite3-dev libncursesw5-dev xz-utils tk-dev \
            libxml2-dev libxmlsec1-dev libjpeg-dev zlib1g-dev autoconf automake libtool pkg-config

      - name: Install buildozer
        run: |
          pip install --upgrade pip setuptools wheel
          pip install buildozer

      - name: Build APK
        run: buildozer android debug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
