name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        pip install --upgrade buildozer

    - name: Build APK
      run: |
        buildozer android debug
      working-directory: ./  # thư mục chứa buildozer.spec

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: ./bin/*.apk
