name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            zip \
            openjdk-8-jdk \
            unzip \
            zlib1g-dev \
            libncurses5:i386 \
            libstdc++6:i386 \
            libgtk2.0-0:i386 \
            libpangox-1.0-0:i386 \
            libpangoxft-1.0-0:i386 \
            libidn11:i386 \
            libssl1.0.0:i386 \
            libcurl3:i386 \
            libsqlite3-0:i386

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk-debug
          path: bin/*.apk
